ZECHARIAH SAMPANG | 2ECE-C

# A. REPRODUCABLE NORMALIZATION PROBLEM


In [2]:
import numpy as np

In [3]:
np.random.seed(2112)

In [4]:
X = np.random.randint(10, 101, size=(5,5))

In [5]:
mean = X.mean()
std = np.std(X)

In [6]:
X_normalized = (X - X.mean())/std

In [7]:
mean_normalized = (X_normalized.mean())
std_normalized = np.std(X_normalized)

*PROBLEM CHECK A:*

In [8]:
print("X:\n",X)
print("\nX_normalized:\n",X_normalized)
print("\nmean:\n",mean)
print("\nStandard Deviation:\n",std)
print("\nNormalized mean:\n",mean_normalized)
print("\nNormalized Standard Deviation:\n",std_normalized)

X:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

X_normalized:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

mean:
 46.36

Standard Deviation:
 25.864075471588002

Normalized mean:
 0.0

Normalized Standard Deviation:
 0.9999999999999999


In [9]:
np.save("X_normalized.npy", X_normalized)

# B. CUBES DIVISIBLE BY 4

In [11]:
integers = np.arange(1,101)

In [12]:
cubed_integers = integers**3

In [13]:
C = cubed_integers.reshape(10,10)

In [14]:
div_by_4 = C[C%4 == 0]

*PROBLEM CHECK B:*

In [15]:
print("The shape of C: \n",C.shape)
print("\nThe array divisible by 4: \n", div_by_4)
print("\nNumber of elements in div_by_4: \n",div_by_4.size)

The shape of C: 
 (10, 10)

The array divisible by 4: 
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of elements in div_by_4: 
 50


In [16]:
np.save("div_by_4.npy", div_by_4)

#C. ABOVE-MEAN SQUARES PROBLEM

In [17]:
bintegers = np.arange(1,37)

In [18]:
S = bintegers**2

In [19]:
S = np.reshape(S,(6,6))

In [20]:
S_mean = S.mean()

In [21]:
above_mean = S[S>S_mean]

*PROBLEM CHECK C:*

In [22]:
print("S: \n",S)
print("\nS_mean:\n",S_mean)
print("\nabove_mean:\n",above_mean)
print("\nThe number of selected elements: \n",above_mean.size)


S: 
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

S_mean:
 450.1666666666667

above_mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

The number of selected elements: 
 15


In [23]:
np.save("above_mean.npy", above_mean)